#!/usr/bin/env php
<?php

/*
 *	Runs a daemon that evaluates the state of business every minute
 */

include('../common/log.class.php');
include('../common/tempd_client.php');
include('../common/heaterd_client.php');

define('TIMEOUT', 1); // Timeout in seconds
//define('LOGFILE', '/var/log/verwarmd/logic.log');
define('LOGFILE', '../tmplog/logic.log');



$log = new Log(LOGFILE);

$log->log('Started logicd');

$state = array(
	'cur_temp' = 0,
	'target_temp' = 0
);

while(true) {

	$state->cur_temp = temp_get_temperature();

	$log->log('Current temperature: '.$state->cur_temp);


	sleep(TIMEOUT);
}
